//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *AgentEvaluationSpec) DeepCopyInto(out *AgentEvaluationSpec) {
	*out = *in
	if in.MinSuccessRate != nil {
		value := *in.MinSuccessRate
		out.MinSuccessRate = &value
	}
	if in.MaxErrorRate != nil {
		value := *in.MaxErrorRate
		out.MaxErrorRate = &value
	}
	if in.MaxP95LatencyMs != nil {
		value := *in.MaxP95LatencyMs
		out.MaxP95LatencyMs = &value
	}
}

func (in *AgentTargetSpec) DeepCopyInto(out *AgentTargetSpec) {
	*out = *in
	if in.APIKeySecretRef != nil {
		out.APIKeySecretRef = in.APIKeySecretRef.DeepCopy()
	}
	if in.Pricing != nil {
		out.Pricing = new(AgentPricingSpec)
		*out.Pricing = *in.Pricing
	}
}

func (in *AgentPricingSpec) DeepCopyInto(out *AgentPricingSpec) { *out = *in }

func (in *AgentTestRun) DeepCopyInto(out *AgentTestRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *AgentTestRun) DeepCopy() *AgentTestRun {
	if in == nil {
		return nil
	}
	out := new(AgentTestRun)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentTestRun) DeepCopyObject() runtime.Object {
	if copy := in.DeepCopy(); copy != nil {
		return copy
	}
	return nil
}

func (in *AgentTestRunList) DeepCopyInto(out *AgentTestRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AgentTestRun, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *AgentTestRunList) DeepCopy() *AgentTestRunList {
	if in == nil {
		return nil
	}
	out := new(AgentTestRunList)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentTestRunList) DeepCopyObject() runtime.Object {
	if copy := in.DeepCopy(); copy != nil {
		return copy
	}
	return nil
}

func (in *AgentTestRunSpec) DeepCopyInto(out *AgentTestRunSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	in.Workload.DeepCopyInto(&out.Workload)
	in.Evaluation.DeepCopyInto(&out.Evaluation)
}

func (in *AgentTestRunStatus) DeepCopyInto(out *AgentTestRunStatus) {
	*out = *in
	if in.StartedAt != nil {
		out.StartedAt = in.StartedAt.DeepCopy()
	}
	if in.CompletionTime != nil {
		out.CompletionTime = in.CompletionTime.DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *AgentWorkloadSpec) DeepCopyInto(out *AgentWorkloadSpec) {
	*out = *in
	in.DatasetRef.DeepCopyInto(&out.DatasetRef)
}

func (in *AgentRunnerSpec) DeepCopyInto(out *AgentRunnerSpec) {
	*out = *in
}
